[theme]
# Primary accent color for interactive elements.
primaryColor = "#A50113"

# Background color for the main content area.
backgroundColor = "#FFFBF2"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#DFE2DB"

# Color used for almost all text.
textColor = "#211D21"